[samples] PriceLimit
masanorihirano/pams pull request #79
Opened 2023-05-30 23:38 UTC by bonochof

https://github.com/masanorihirano/pams/issues/37

2023-05-31 06:08 UTC, masanorihirano requested changes

2023-05-31 06:08 UTC, masanorihirano commented on pams/events/price_limit_rule.py
> +        self.reference_price = self.reference_market.get_market_price()
元の実装に合わせて作ってくれたと理解していますが，この，get_market_price()，初期化の順番によっては，setupで取得するのは少々危険です．現状では，marketの初期化より後に来ますが，並列化するときのボトルネックになり得ます．
こういう，元の実装の悪いところは，実装を変更する価値があると思います．
たとえば，get_market_price(time=0)っでreference_priceをget_limited_priceの内部でとるのもありかもしれません．
そこまでくると，referenceTimeというconfig.jsonを外部引数でOptionalで与えたくなってきますかね...？

2023-05-31 06:08 UTC, masanorihirano commented on samples/price_limit/config.json
> +}
ファイル末尾に改行が不足しています

2023-05-31 06:11 UTC, masanorihirano commented
@bonochof 

お願いしたいこと①
https://github.com/masanorihirano/pams/blob/ba35f7888e3a8c22c8231de9e2f286fc4ecf25d1/docs/source/user_guide/config.rst?plain=1#L31-L38
こんな感じに，メモ程度に追加部分のconfig，足してもらえますか？とりあえず雑でよいです．

お願いしたいこと② (Optional)
https://github.com/masanorihirano/pams/blob/main/tests/pams/events/test_fundamental_price_shock.py
雑でいいので，こんな感じで，テストを追加できますか？
(正直，正しくraise Errorされているか確かめてほしい程度です．)
難しければ，無理しなくてよいです．

2023-05-31 06:14 UTC, masanorihirano commented on pams/events/price_limit_rule.py
> +                                       This can include the parameters "enabled" and "shockTimeLength".
docstring間違ってない？

2023-05-31 06:15 UTC, masanorihirano commented on pams/events/price_limit_rule.py
> +                                       This can include the parameters "enabled" and "shockTimeLength".
docstring，間違ってない？

2023-05-31 06:18 UTC, masanorihirano commented on pams/events/price_limit_rule.py
> +    trigger_change_rate: float
元の実装と合わせるために，念のため，actiovation_countを実装できますか？

2023-05-31 06:23 UTC, masanorihirano commented on samples/price_limit/config.json
> +		"targetMarkets": ["Market"],
targetMarketsって，どこに使われている？？？(元の実装のミス？？？)
もしかすると，referenceMarketをobsolateして，targetMarketsを採用した方がいいかも

2023-05-31 06:24 UTC, masanorihirano commented on samples/price_limit/config.json
> +		"targetMarkets": ["Market"],
(互換性を持たせてobsolateする場合は，そのkeyが設定されてたらwarningを出せばよいです．)

2023-05-31 06:28 UTC, masanorihirano commented on pams/events/price_limit_rule.py
> +                event=self, hook_type="market", is_before=True, time=None
これだと，複数マーケットがある場合に，73行でAssertionError出してしまうと思うので，specific_instranceでtargetのマーケットをインスタンス指定した方がいいかも．複数targetの場合は，EventHookをinstanceごとに作ってlistで投げつければOKのはずです

2023-06-22 05:53 UTC, closed without merging

2023-06-22 05:54 UTC, bonochof commented on pams/events/price_limit_rule.py
> +        self.reference_price = self.reference_market.get_market_price()
https://github.com/masanorihirano/pams/pull/81#issuecomment-1602045248

2023-06-22 05:55 UTC, bonochof commented on samples/price_limit/config.json
> +}
https://github.com/masanorihirano/pams/pull/81#issuecomment-1602045620

2023-06-22 05:55 UTC, bonochof commented on pams/events/price_limit_rule.py
> +                                       This can include the parameters "enabled" and "shockTimeLength".
https://github.com/masanorihirano/pams/pull/81#issuecomment-1602046877

2023-06-22 05:55 UTC, bonochof commented on pams/events/price_limit_rule.py
> +    trigger_change_rate: float
https://github.com/masanorihirano/pams/pull/81#issuecomment-1602047244

2023-06-22 06:08 UTC, bonochof commented on samples/price_limit/config.json
> +		"targetMarkets": ["Market"],
https://github.com/masanorihirano/pams/pull/81#issuecomment-1602061378

2023-06-22 06:10 UTC, bonochof commented on pams/events/price_limit_rule.py
> +                event=self, hook_type="market", is_before=True, time=None
https://github.com/masanorihirano/pams/pull/81#issuecomment-1602062541