[samples] TradingHalt
masanorihirano/pams pull request #80
Opened 2023-05-31 02:27 UTC by bonochof

https://github.com/masanorihirano/pams/issues/37

2023-05-31 06:45 UTC, masanorihirano requested changes

2023-05-31 06:45 UTC, masanorihirano commented on pams/events/trading_halt_rule.py
> +        self.reference_price = self.reference_market.get_market_price()
price limitの方で指摘したのと同じで，実装を変えた方がいいかも

2023-05-31 06:45 UTC, masanorihirano commented on pams/events/trading_halt_rule.py
> +                                       This can include the parameters "enabled" and "shockTimeLength".
docstring，こちらも直してください．

2023-05-31 06:45 UTC, masanorihirano commented on pams/events/trading_halt_rule.py
> +                    for i in range(self.halting_time_length)
この時間指定はマズいです．EventHookはsimulatorの生成段階で，Hookをregisterするので，その際に時刻の計算を行ってdictに保存します．なので，ここでtimeはNoneとして，すべての時刻でひっかけて，hooked_after_orderでひっかけた方がいいです

2023-05-31 06:45 UTC, masanorihirano commented on pams/events/trading_halt_rule.py
> +                    for i in range(self.halting_time_length)
たぶん，なのですが，haltが起こるのは，executionの直後，haltが解除されるのは，market stepが始まる前，なので，
execution after (hooked_after_execution) と market before (hooked_before_step_for_market)をhookした方がいい気がします．あと，こちらも，instranceの指定をしておいた方が良いかと

2023-05-31 06:45 UTC, masanorihirano commented on samples/trading_halt/config.json
> +		"targetMarkets": ["Market"],
これも，referenceMarketをobsolateにしていいかも

2023-05-31 06:45 UTC, masanorihirano commented on samples/trading_halt/config.json
> +}
末尾に改行追加

2023-06-23 05:33 UTC, bonochof commented on pams/events/trading_halt_rule.py
> +        self.reference_price = self.reference_market.get_market_price()
こちらのCommitで対応しました．
https://github.com/masanorihirano/pams/pull/80/commits/3b539ca2a2d4f6d9fd9ed00424e73644559869fa

2023-06-23 05:34 UTC, bonochof commented on pams/events/trading_halt_rule.py
> +                                       This can include the parameters "enabled" and "shockTimeLength".
こちらのCommitで対応しました．
https://github.com/masanorihirano/pams/pull/80/commits/86f881d362f43a765c466909cc2d593084b8dcbd

2023-06-23 05:35 UTC, bonochof commented on pams/events/trading_halt_rule.py
> +                    for i in range(self.halting_time_length)
こちらのCommitで対応しました．（instanceの設定についてはちょっとよくわからなかったので一旦放置しています．）
https://github.com/masanorihirano/pams/pull/80/commits/40500f536b8a35584ecda7688c6a374e7ec3329d

2023-06-23 05:35 UTC, bonochof commented on samples/trading_halt/config.json
> +		"targetMarkets": ["Market"],
こちらのCommitで対応しました．
https://github.com/masanorihirano/pams/pull/80/commits/69073aadbea3b8a112d0c1e1d97dd1fca2a0846d

2023-06-23 05:35 UTC, bonochof commented on samples/trading_halt/config.json
> +}
こちらのCommitで対応しました．
https://github.com/masanorihirano/pams/pull/80/commits/1d776fee1c9329fbd14675f826f36c64177929db

2023-06-27 17:10 UTC, bonochof commented on pams/events/trading_halt_rule.py
> +                    for i in range(self.halting_time_length)
instanceの設定，およびeventの修正・確認完了しました．
https://github.com/masanorihirano/pams/pull/80/commits/575261ecc25f2b9c9055b6d74189db5c52e6ccc2

2023-06-30 17:24 UTC, masanorihirano approved these changes

2023-06-30 17:24 UTC, merged